// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-7BfNr1x5gvyLTP5Joe9_h6LSpAZ-AVc',
    appId: '1:928368040297:web:977eb95c6165a30c3985f8',
    messagingSenderId: '928368040297',
    projectId: 'flutter-shop-52848',
    authDomain: 'flutter-shop-52848.firebaseapp.com',
    storageBucket: 'flutter-shop-52848.firebasestorage.app',
    measurementId: 'G-NKTXDVP59B',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3pzaFM98uGUcsVnEdNaYaeOl_pojiHlQ',
    appId: '1:928368040297:ios:e43f6858422f8cb43985f8',
    messagingSenderId: '928368040297',
    projectId: 'flutter-shop-52848',
    storageBucket: 'flutter-shop-52848.firebasestorage.app',
    iosBundleId: 'com.example.montherShopMobileFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-7BfNr1x5gvyLTP5Joe9_h6LSpAZ-AVc',
    appId: '1:928368040297:web:977eb95c6165a30c3985f8',
    messagingSenderId: '928368040297',
    projectId: 'flutter-shop-52848',
    authDomain: 'flutter-shop-52848.firebaseapp.com',
    storageBucket: 'flutter-shop-52848.firebasestorage.app',
    measurementId: 'G-NKTXDVP59B',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pzaFM98uGUcsVnEdNaYaeOl_pojiHlQ',
    appId: '1:928368040297:ios:e43f6858422f8cb43985f8',
    messagingSenderId: '928368040297',
    projectId: 'flutter-shop-52848',
    storageBucket: 'flutter-shop-52848.firebasestorage.app',
    iosBundleId: 'com.example.montherShopMobileFlutter',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk2HciPCKO_93PKACpHW4iey9i1r4YYGo',
    appId: '1:928368040297:android:406bad2bac675c7b3985f8',
    messagingSenderId: '928368040297',
    projectId: 'flutter-shop-52848',
    storageBucket: 'flutter-shop-52848.firebasestorage.app',
  );

}